version: '3.3'

services:
    mysqldb:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db:/var/lib/mysq
        networks:
            - web

    wordpress:
        container_name: ${COMPOSE_PROJECT_NAME}-wordpress
        depends_on:
            - mysqldb
        image: wordpress:latest
        restart: always
        volumes:
            - wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: ${COMPOSE_PROJECT_NAME}-db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${HTTP_HOST}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
        networks:
            - web
volumes:
    wordpress:
    db:

networks:
    web:
        external: true
