version: '3.3'

services:
    mysqldb:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - web

    wordpress:
        depends_on:
            - mysqldb
        image: wordpress:latest
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysqldb:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wpSecureP@ssw0rd
            WORDPRESS_DB_NAME: wordpress
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${HTTP_HOST}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
        networks:
            - web


networks:
    web:
        external: true
